"""Turn the adapt IR into files the user owns.

Two artifacts: the A2A 1.0 Agent Card, and a standalone server that imports the
user's own agent and serves it. Nothing here mutates the agent — adaptation is
additive, which is the whole point of "don't rewrite your agents".
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from superoptix.protocols.a2a.adapt.base import AgentSpec
from superoptix.protocols.a2a.card_builder import build_a2a_agent_card_payload

RPC_URL = "/a2a/jsonrpc"

_SERVER_TEMPLATE = '''"""A2A 1.0 server for {name}.

Generated by `super a2a adapt` from {entrypoint} ({framework}).
This file is yours: edit it, commit it, deploy it anywhere. It imports your
agent unchanged — adapting it did not modify your code.

    uvicorn {module_stem}:app --port 8000
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, AsyncIterator, Dict

from superoptix.protocols.a2a.adapt.base import load_entrypoint
from superoptix.protocols.a2a.adapt.invoke import invoke_agent
from superoptix.protocols.a2a.server import create_a2a_fastapi_app
from superoptix.runtime.base import RuntimeContext
from superoptix.runtime.registry import runtime_registry

ENTRYPOINT = {entrypoint!r}
FRAMEWORK = {framework!r}
PUBLIC_URL = {public_url!r}
CARD_PATH = Path(__file__).resolve().parent / "agent-card.json"


class AdaptedAgentRuntime:
    """Bridges the A2A server to your agent."""

    def __init__(self, target: Any = None) -> None:
        self._agent = None

    def _resolve(self) -> Any:
        if self._agent is None:
            self._agent = load_entrypoint(ENTRYPOINT)
        return self._agent

    async def invoke(
        self, inputs: Dict[str, Any], context: RuntimeContext | None = None
    ) -> Dict[str, Any]:
        query = str(inputs.get("query") or inputs.get("input") or "")
        return await invoke_agent(self._resolve(), FRAMEWORK, query)

    async def stream(
        self, inputs: Dict[str, Any], context: RuntimeContext | None = None
    ) -> AsyncIterator[Dict[str, Any]]:
        yield await self.invoke(inputs, context=context)

    async def cancel(self, task_id: str, context: RuntimeContext | None = None) -> bool:
        return False

    async def metadata(self) -> Dict[str, Any]:
        return {{"metadata": {{"name": {name!r}}}, "spec": {{"tasks": []}}}}

    async def capabilities(self) -> Dict[str, Any]:
        return {{"streaming": True, "cancel": False, "task_context": True}}


runtime_registry.register("adapted_agent", AdaptedAgentRuntime)

with CARD_PATH.open(encoding="utf-8") as handle:
    AGENT_CARD = json.load(handle)

app = create_a2a_fastapi_app(
    pipeline=None,
    agent_url=PUBLIC_URL,
    rpc_url={rpc_url!r},
    runtime_adapter="adapted_agent",
    agent_card=AGENT_CARD,
)
'''


def build_card(spec: AgentSpec, *, public_url: str) -> Dict[str, Any]:
    """A2A 1.0 Agent Card for an adapted agent."""
    return build_a2a_agent_card_payload(
        metadata={
            "name": spec.name,
            "description": spec.description,
            "version": spec.version,
        },
        spec={},
        agent_url=public_url,
        rpc_url=RPC_URL,
        protocol_version="1.0",
        # The installed base is on 0.3; advertising both keeps pre-1.0
        # orchestrators able to negotiate instead of skipping the agent.
        legacy_protocol_version="0.3",
        skills_override=[s.to_card_skill() for s in spec.skills],
    )


def emit(
    spec: AgentSpec,
    out_dir: Path,
    *,
    public_url: str,
    server_filename: str = "a2a_server.py",
) -> List[Path]:
    """Write the card, the server and the generated IR. Returns written paths."""
    out_dir = Path(out_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []

    card_path = out_dir / "agent-card.json"
    card_path.write_text(
        json.dumps(build_card(spec, public_url=public_url), indent=2) + "\n",
        encoding="utf-8",
    )
    written.append(card_path)

    server_path = out_dir / server_filename
    server_path.write_text(
        _SERVER_TEMPLATE.format(
            name=spec.name,
            entrypoint=spec.entrypoint,
            framework=spec.framework,
            public_url=public_url.rstrip("/"),
            rpc_url=RPC_URL,
            module_stem=Path(server_filename).stem,
        ),
        encoding="utf-8",
    )
    written.append(server_path)

    # The IR is written too: it is what GEPA optimises later, and it lets a
    # user see and hand-correct how their agent was read.
    spec_path = out_dir / "agentspec.json"
    spec_path.write_text(json.dumps(spec.to_dict(), indent=2) + "\n", encoding="utf-8")
    written.append(spec_path)

    return written
